query Song($song: String) {
  song(where: { songId: $song }) {
    songId
    song
    artist
    cover
    length
    mp3
    homeTown
    formed
    biography
    logo
    presets {
      name
      at
      pc
    }
    artwork {
      bg
      cloudinaryTransform
      opacity
      x
      y
    }
  }
}
