query Songs {
  songs(orderBy: publishedAt_DESC) {
    songId
    song
    artist
    cover
    length
    mp3
    presets {
      name
      at
      pc
    }
    artwork {
      bg
      cloudinaryTransform
      opacity
      x
      y
    }
  }
}
