query Songs {
  all_song(order_by: created_at_DESC) {
    items {
      title
      song
      songid
      artist
      biography
      cover
      formed
      home_town
      length
      logo
      mp3
      artwork {
        imageConnection {
          edges {
            node {
              url
            }
          }
        }
      }
      presets {
        at
        name
        pc
      }
    }
  }
}
